version: '3.9'

services:
  db:
    image: mysql:8.3.0
    ports:
      - '127.0.0.1:3306:3306'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    env_file:
      - .env
    ports:
      - '127.0.0.1:8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

  redis:
    image: redis
    container_name: redis_main
    ports:
    - '127.0.0.1:6379:6379'

volumes:
  db-data: